dist: xenial
sudo: enabled

language: python

cache:
  - pip
  - ccache

# https://docs.travis-ci.com/user/languages/cpp/
matrix:
  include:
    - os: linux
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
      - PCL_VERSION="1.8"
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - sudo apt-get install --allow-unauthenticated -qq libpcl-dev

install:
#  - if [[ ( "$TRAVIS_OS_NAME" == "linux" ) ]]; then
#      sudo add-apt-repository -y ppa:webupd8team/java && sudo apt update && sudo apt -y install oracle-java8-installer;
#
#      sudo apt-get install zram-config;
#
#      sudo apt -y install g++ doxygen mpi-default-dev openmpi-bin openmpi-common libusb-1.0-0-dev libqhull* libusb-dev libgtest-dev;
#      sudo apt -y install git-core freeglut3-dev pkg-config build-essential libxmu-dev libxi-dev libphonon-dev libphonon-dev phonon-backend-gstreamer;
#      sudo apt -y install phonon-backend-vlc graphviz mono-complete qt-sdk libflann-dev libflann1.8 libboost-all-dev libeigen3-dev;
#
#      wget --no-check-certificate -qO- http://www.cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz -O /tmp/cmake-3.6.2-Linux-x86_64.tar.gz;
#      tar -xvf /tmp/cmake-3.6.2-Linux-x86_64.tar.gz;
#      export PATH=$PWD/cmake-3.6.2-Linux-x86_64/bin/:$PATH;
#
#      sudo dd if=/dev/zero of=/swapfile bs=1024 count=4194304;
#      sudo mkswap /swapfile;
#      sudo swapon /swapfile;
#
#      sudo apt-get install ninja-build;
#
#      wget https://github.com/PointCloudLibrary/pcl/archive/pcl-1.8.0.tar.gz;
#      tar -xf pcl-1.8.0.tar.gz;
#      cd pcl-pcl-1.8.0 && mkdir build && cd build;
#      cmake -G Ninja -DWITH_OPENGL:BOOL=OFF -DWITH_FZAPI:BOOL=OFF -DWITH_LIBUSB:BOOL=OFF -DWITH_VTK:BOOL=OFF -DBUILD_OPENNI:BOOL=OFF -DBUILD_OPENNI2:BOOL=OFF -DBUILD_apps:BOOL=OFF -DBUILD_geometry:BOOL=OFF -DBUILD_global_tests:BOOL=OFF -DBUILD_outofcore:BOOL=OFF -DBUILD_people:BOOL=OFF -DBUILD_tools:BOOL=OFF -DBUILD_tracking:BOOL=OFF -DBUILD_visualization:BOOL=OFF -DBUILD_examples:BOOL=OFF ..;
#
#      travis_wait 50 ninja -j4;
#      sudo ninja -t targets install;
#      cd ../..;
#    fi
  - python setup.py build_ext -i
